/**
 * This file is a part of AGE OF CRAFTERS. If you're using a portion of code or code edited using this file's code as base, you
 * must mention that in the site you're uploading your mod, or in the mcmod.info credits.
 * CODED & TEXTURED BY QUACKIE_THE_DUCK and SSILVAMC
 * CONTENT IDEAS BY SSILVAMC, QUACKIE_THE_DUCK, KOOKYBOY9 and SO MUCH MORE
 * IDEAS from WIKIPEDIA.ORG, BEN-HUR: A TALE OF CHRIST, AGE OF EMPIRES SERIES by MICROSOFT CORPORATION
 * 
 */
package ss.ageofcrafters.main;

import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemBlock;
import net.minecraft.world.World;
import ss.ageofcrafters.blocks.*;
import ss.ageofcrafters.blocks.itemblocks.*;
import ss.ageofcrafters.blocks.slabs.*;
import ss.ageofcrafters.blocks.walls.*;
import cpw.mods.fml.common.registry.GameRegistry;

public class AgeOfCraftersBlocks {

	public static Block AoCLog;
	public static Block AoBSaplings;
	public static Block AoCPlanks;
	public static Block PlatinumOre;
	public static Block JadeOre;
	public static Block TinOre;
	public static Block CopperOre;
	public static Block BronzeBlock;
	public static Block PlatinumBlock;
	public static Block RedSteelBlock;
	public static Block SteelBlock;
	public static Block ConePineLeaves;
	public static Block PineLeaves;
	public static Block GrapeCrop;
	public static Block Bindweed;
	public static Block Designer;
	public static Block WorkingDesigner;
	public static Block BoneBlock;
	public static Block ChainBlock;  
	public static Block GobletBlock;
	public static Block AsianDoor;
	public static Block LapisBricks;
	public static Block SmoothstoneBricks;
	public static Block AncientBricks;
	public static Block ObsidianBricks;
	public static Block QuartzBricks;
	public static Block JadeBricks;
	public static Block ZigguratBricks;
	public static Block SnowBricks;
	public static Block DirtBricks;
	public static Block SandstoneBricks;
	public static Block EnderBricks;
	public static Block JadePillar;
	public static Block OldStonePillar;
	public static Block SmoothstonePillar;
	public static Block ObsidianPillar;
	public static Block SnowPillar;
	public static Block DirtPillar;
	public static Block ZigguratPillar;
	public static Block EnderPillar;
	public static Block LapisPillar;
	public static Block StonebrickPillar;
	public static Block SandstonePillar;
	public static Block SandstoneBrickStairs;
	public static Block LapisBrickStairs;
	public static Block ObsidianBrickStairs;
	public static Block QuartzBrickStairs;
	public static Block SmoothstoneStairs;
	public static Block AncientBrickStairs;
	public static Block ZigguratBrickStairs;
	public static Block SnowBrickStairs;
	public static Block DirtBrickStairs;
	public static Block EnderBrickStairs;
	public static Block JadeBrickStairs;
	public static Block ObsidianBrickWall;
	public static Block QuartzBrickWall;
	public static Block JadeBrickWall;
	public static Block StoneBrickWall;
	public static Block AncientBrickWall;
	public static Block ZigguratBrickWall;
	public static Block DirtBrickWall;
	public static Block SnowBrickWall;
	public static Block EnderBrickWall;
	public static Block SandstoneBrickWall;
	public static Block SmoothstoneBrickWall;
	public static Block LapisBrickWall;
	public static Block AlloyingTable;
	public static Block WorkingAlloyingTable;
	public static Block Altar;
	public static Block WorkingAltar;
	public static Block WineGobletBlock;
	public static Block PineWoodStairs;
	public static Block WallCarpetWhite;
	public static Block WallCarpetRed;
	public static Block WallCarpetCyan;
	public static Block WallCarpetBlack;
	public static Block WallCarpetBlue;
	public static Block WallCarpetYellow;
	public static Block WallCarpetLightGray;
	public static Block WallCarpetGray;
	public static Block WallCarpetBrown;
	public static Block WallCarpetOrange;
	public static Block WallCarpetMagenta;
	public static Block WallCarpetPurple;
	public static Block WallCarpetLightBlue;
	public static Block WallCarpetPink;
	public static Block WallCarpetGreen;
	public static Block WallCarpetLime;
	public static Block WallCarpetPersianLeft;
	public static Block WallCarpetPersianRight;
	public static Block CarpetDesigned0;
	public static Block CarpetDesigned1;
	public static Block CarpetDesigned2;
	public static Block CarpetDesigned3;
	public static Block AncientHalfSlab;
	public static Block AncientDoubleSlab;
	public static Block	ObsidianHalfSlab;
	public static Block ObsidianDoubleSlab;
	public static Block JadeHalfSlab;
	public static Block JadeDoubleSlab;
	public static Block QuartzHalfSlab;
	public static Block QuartzDoubleSlab;
	public static Block LapisHalfSlab;
	public static Block LapisDoubleSlab;
	public static Block DirtHalfSlab;
	public static Block DirtDoubleSlab;
	public static Block SnowHalfSlab;
	public static Block SnowDoubleSlab;
	public static Block EnderHalfSlab;
	public static Block EnderDoubleSlab;
	public static Block SandstoneHalfSlab;
	public static Block SandstoneDoubleSlab;
	public static Block ZigguratHalfSlab;
	public static Block ZigguratDoubleSlab;
	public static Block ChiseledZigguratBricks;
	public static Block ChiseledSnowBricks;
	public static Block ChiseledSandstoneBricks;
	public static Block ChiseledAncientBricks;
	public static Block ChiseledDirtBricks;
	public static Block ChiseledQuartzBricks;
	public static Block ChiseledLapisBricks;
	public static Block ChiseledJadeBricks;
	public static Block ChiseledObsidianBricks;
	public static Block ChiseledEnderBricks;
	public static Block PineDoubleSlab;
	public static Block PineHalfSlab;
	public static Block PineWoodFence;
	public static Block RedTiles;
	public static Block WhiteTiles;
	public static Block BlueTiles;
	public static Block RedTileStairs;
	public static Block WhiteTileStairs;
	public static Block BlueTileStairs;
	public static Block Amphora;
	public static Block Crater;
	public static Block CyanTiles;
	public static Block CyanTileStairs;
	public static Block Ballista;
	public static Block OliveLeaves;
	
	private static World world;
	private static int y;
	private static int x;
	private static int z;
	
	public static CreativeTabs TabMain = AgeOfCrafters.TabMain;
	public static CreativeTabs TabSpawners = AgeOfCrafters.TabSpawners;


	

	
	static final float stone = Blocks.stone.getBlockHardness(world, x, y, z);
	static final float obsidian = Blocks.obsidian.getBlockHardness(world, x, y, z);
	static final float wood = Blocks.planks.getBlockHardness(world, x, y, z);
	static final float dirt = Blocks.dirt.getBlockHardness(world, x, y, z);
	static final float snow = Blocks.snow.getBlockHardness(world, x, y, z);

	
	public static void init(){
		ChainBlock = new BlockChainBlock(Material.glass).setCreativeTab(TabMain).setBlockName("AoBBlocks-chain").setHardness(wood / 2 + (wood / 4)).setResistance(3F);
		BoneBlock = new BlockBoneBlock(Material.rock).setBlockName("AoBBlocks-bone").setCreativeTab(TabMain).setHardness(3F).setResistance(5F);
		Designer = new BlockDesigner(Material.rock, false).setCreativeTab(TabMain).setHardness(3F).setResistance(5F).setBlockName("AoBDesigners-default");
		WorkingDesigner = new BlockDesigner(Material.rock, true).setHardness(3F).setResistance(5F).setBlockName("AoBDesigners-default.working");
		PlatinumOre = new BlockPlatinumOre(Material.rock).setHardness(3F).setBlockName("AoBOres-platinum").setCreativeTab(TabMain).setResistance(5F);
		JadeOre = new BlockJadeOre(Material.rock).setHardness(3F).setBlockName("AoBOres-jade").setCreativeTab(TabMain).setResistance(5F);
		TinOre = new BlockTinOre(Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoBOres-tin");
		CopperOre = new BlockCopperOre(Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoBOres-copper");
		LapisBricks = new BlockAoCBricks(Material.rock).setHardness(2.1F).setBlockName("AoBBricks.lapis").setCreativeTab(TabMain);
		SmoothstoneBricks = new BlockAoCBricks(Material.rock).setHardness(2.3F).setBlockName("AoBBricks.smoothstone").setCreativeTab(TabMain);
		AncientBricks = new BlockAoCBricks(Material.rock).setHardness(2.1f).setBlockName("AoBBricks.ancient").setCreativeTab(TabMain);
		ObsidianBricks = new BlockAoCBricks(Material.rock).setHardness(Blocks.obsidian.getBlockHardness(world, x, y, z)).setBlockName("AoBBricks.obsidian").setCreativeTab(TabMain);
		QuartzBricks = new BlockAoCBricks(Material.rock).setHardness(2.3F).setBlockName("AoBBricks.quartz").setCreativeTab(TabMain);
		JadeBricks = new BlockAoCBricks(Material.rock).setHardness(2.3F).setBlockName("AoBBricks.jade").setCreativeTab(TabMain);
		ZigguratBricks = new BlockAoCBricks(Material.rock).setHardness(2.3F).setBlockName("AoBBricks.ziggurat").setCreativeTab(TabMain);
		SnowBricks = new BlockAoCBricks(Material.craftedSnow).setHardness(snow).setBlockName("AoBBricks.snow").setCreativeTab(TabMain);
		DirtBricks = new BlockAoCBricks(Material.ground).setHardness(0.4F).setBlockName("AoBBricks.dirt").setCreativeTab(TabMain);
		SandstoneBricks = new BlockAoCBricks(Material.rock).setHardness(2.3F).setBlockName("AoBBricks.sandstone").setCreativeTab(TabMain);
		EnderBricks = new BlockAoCBricks(Material.rock).setHardness(2.3F).setBlockName("AoBBricks.ender").setCreativeTab(TabMain);
		SmoothstoneStairs=new BlockAoCStairs(Material.rock, Blocks.double_stone_slab, 8).setHardness(3F).setBlockName("AoBStairs-smoothstone").setCreativeTab(TabMain).setResistance(5F);
		SandstoneBrickStairs = new BlockAoCStairs(Material.rock, SandstoneBricks, 0).setCreativeTab(TabMain).setHardness(stone).setBlockName("AoBStairs-sandstone");
		ZigguratBrickStairs = new BlockAoCStairs(Material.rock, ZigguratBricks, 0).setCreativeTab(TabMain).setHardness(stone).setBlockName("AoBStairs-ziggurat");
		LapisBrickStairs = new BlockAoCStairs(Material.rock, LapisBricks, 0).setCreativeTab(TabMain).setHardness(stone).setBlockName("AoBStairs-lapis");
		ObsidianBrickStairs = new BlockAoCStairs(Material.rock, ObsidianBricks, 0).setCreativeTab(TabMain).setHardness(obsidian).setBlockName("AoBStairs-obsidian");
		QuartzBrickStairs = new BlockAoCStairs(Material.rock, QuartzBricks, 0).setCreativeTab(TabMain).setHardness(stone).setBlockName("AoBStairs-quartz");
		AncientBrickStairs = new BlockAoCStairs(Material.rock, AncientBricks, 0).setCreativeTab(TabMain).setHardness(stone - 0.2f).setBlockName("AoBStairs-ancient");
		DirtBrickStairs = new BlockAoCStairs(Material.ground, DirtBricks, 0).setCreativeTab(TabMain).setHardness(dirt).setBlockName("AoBStairs-dirt");
		SnowBrickStairs = new BlockAoCStairs(Material.craftedSnow, SnowBricks, 0).setCreativeTab(TabMain).setHardness(snow).setBlockName("AoBStairs-snow");
		EnderBrickStairs = new BlockAoCStairs(Material.rock, EnderBricks, 0).setCreativeTab(TabMain).setHardness(stone).setBlockName("AoBStairs-ender");
		JadeBrickStairs = new BlockAoCStairs(Material.rock, JadeBricks, 0).setCreativeTab(TabMain).setHardness(stone).setBlockName("AoBStairs-jade");
		AoCLog = new BlockAoCLog(Material.wood).setHardness(2F).setBlockName("AoBLogs").setCreativeTab(TabMain).setResistance(2F);	
		AoCPlanks = new BlockAoCPlanks(Material.wood).setHardness(2.2F).setBlockName("AoBPlanks").setCreativeTab(TabMain).setResistance(5F);
		JadePillar = new BlockAoCPillars(Material.rock, new String[] {"jade"}).setBlockName("AoBPillars.jade").setHardness(stone).setCreativeTab(TabMain); 
		OldStonePillar = new BlockAoCPillars(Material.rock ,new String[] {"ancient"}).setBlockName("AoBPillars.ancient").setHardness(stone - 0.2f).setCreativeTab(TabMain);
		SmoothstonePillar = new BlockAoCPillars(Material.rock, new String[] {"smoothstone"}).setBlockName("AoBPillars.smoothstone").setHardness(stone).setCreativeTab(TabMain);
		ZigguratPillar = new BlockAoCPillars(Material.rock, new String[] {"ziggurat"}).setHardness(stone).setBlockName("AoBPillars.ziggurat").setCreativeTab(TabMain);
		LapisPillar = new BlockAoCPillars(Material.rock, new String[] {"lapis"}).setHardness(stone).setBlockName("AoBPillars.lapis").setCreativeTab(TabMain);
		ObsidianPillar = new BlockAoCPillars(Material.rock, new String[] {"obsidian"}).setBlockName("AoBPillars.obsidian").setHardness(obsidian).setCreativeTab(TabMain);
		SnowPillar = new BlockAoCPillars(Material.craftedSnow, new String[] {"snow"}).setBlockName("AoBPillars.snow").setHardness(snow).setCreativeTab(TabMain);
		DirtPillar = new BlockAoCPillars(Material.ground, new String[] {"dirt"}).setBlockName("AoBPillars.dirt").setHardness(dirt).setCreativeTab(TabMain);
		EnderPillar = new BlockAoCPillars(Material.rock, new String[] {"ender"}).setBlockName("AoBPillars.ender").setHardness(stone).setCreativeTab(TabMain);
		StonebrickPillar = new BlockAoCPillars(Material.rock,new String[] {"stonebrick"}).setBlockName("AoBPillars.stonebrick").setHardness(stone).setCreativeTab(TabMain);
		EnderBrickWall = new BlockEnderBrickWall(EnderBricks, Material.rock).setBlockName("AoBWalls.ender").setCreativeTab(TabMain);
		ObsidianBrickWall = new BlockObsidianBrickWall(ObsidianBricks, Material.rock).setBlockName("AoBWalls-obsidian").setCreativeTab(TabMain);
		JadeBrickWall = new BlockJadeBrickWall(JadeBricks, Material.rock).setBlockName("AoBWalls-jade").setCreativeTab(TabMain);
		LapisBrickWall = new BlockLapisBrickWall(LapisBricks, Material.rock).setBlockName("AoBWalls-lapis").setCreativeTab(TabMain);
		SmoothstoneBrickWall = new BlockSmoothstoneBrickWall(SmoothstoneBricks, Material.rock).setBlockName("AoBWalls-smoothstone").setCreativeTab(TabMain);
		StoneBrickWall = new BlockStoneBrickWall(Blocks.stonebrick, Material.rock).setBlockName("AoBWalls-stonebrick").setCreativeTab(TabMain);
		QuartzBrickWall = new BlockQuartzBrickWall(QuartzBricks, Material.rock).setBlockName("AoBWalls-quartz").setCreativeTab(TabMain);
		ZigguratBrickWall = new BlockZigguratBrickWall(ZigguratBricks, Material.rock).setBlockName("AoBWalls-ziggurat").setCreativeTab(TabMain);
		AncientBrickWall = new BlockAncientBrickWall(AncientBricks, Material.rock).setBlockName("AoBWalls-ancient").setCreativeTab(TabMain);
		DirtBrickWall = new BlockDirtBrickWall(DirtBricks, Material.ground).setBlockName("AoBWalls-dirt").setCreativeTab(TabMain);
		SnowBrickWall = new BlockSnowBrickWall(SnowBricks, Material.craftedSnow).setBlockName("AoBWalls-snow").setCreativeTab(TabMain);
		SandstoneBrickWall = new BlockSandstoneBrickWall(SandstoneBricks, Material.rock).setBlockName("AoBWalls-sandstone").setCreativeTab(TabMain);
		AlloyingTable = new BlockAlloyingTable(Material.rock, false).setCreativeTab(TabMain).setHardness(stone).setBlockName("AlloyingTable");
		WorkingAlloyingTable = new BlockAlloyingTable(Material.rock, true).setCreativeTab(TabMain).setHardness(stone).setBlockName("AlloyingTable.working");
		GobletBlock = new BlockGoblet(Material.wood).setBlockName("Goblet-block").setHardness(wood);	
		AsianDoor = new BlockAsianDoor(Material.wood).setBlockName("AsianDoor").setHardness(wood);
		AoBSaplings = new BlockAoCSaplings(Material.plants).setHardness(0F).setBlockName("AoBSaplings").setCreativeTab(TabMain).setResistance(0F);
		PineLeaves = new BlockPineLeaves(Material.leaves).setHardness(dirt - 0.1f).setBlockName("AoBLeaves-pine").setCreativeTab(TabMain).setResistance(0.1F);
		ConePineLeaves = new BlockConePineLeaves(Material.leaves).setHardness(dirt - 0.1f).setBlockName("AoBLeaves-pine2").setCreativeTab(TabMain).setResistance(0.1F);		
		Bindweed = new BlockBindweed(Material.plants).setBlockName("AoBBlocks-bindweed").setCreativeTab(TabMain);		
		BronzeBlock = new BlockOreBlock(Material.rock).setHardness(stone).setBlockName("AoBOreBlocks-bronze").setCreativeTab(TabMain);
		SteelBlock = new BlockOreBlock(Material.rock).setHardness(stone).setBlockName("AoBOreBlocks-steel").setCreativeTab(TabMain);
		PlatinumBlock = new BlockOreBlock(Material.rock).setHardness(stone).setBlockName("AoBOreBlocks-platinum").setCreativeTab(TabMain);
		RedSteelBlock = new BlockOreBlock(Material.rock).setHardness(stone).setBlockName("AoBOreBlocks-redSteel").setCreativeTab(TabMain);	
		GrapeCrop = new BlockGrapeCrop().setBlockName("AoBCrops-grape").setHardness(0.05F);
		Altar = new BlockAltar(Material.rock, false).setBlockName("Altar").setHardness(stone).setCreativeTab(TabMain);
		WorkingAltar = new BlockAltar(Material.rock, true).setBlockName("WorkingAltar").setHardness(stone).setLightLevel(1f).setCreativeTab(TabMain);
		WineGobletBlock = new BlockWineGoblet(Material.wood).setBlockName("WineGoblet-block").setHardness(wood);	
		PineWoodStairs = new BlockAoCStairs(Material.wood, AoCPlanks, 0).setBlockName("PineWoodStairs").setHardness(wood).setCreativeTab(TabMain);
		WallCarpetWhite = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-white").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetRed = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-red").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetBlue = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-blue").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetYellow = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-yellow").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetGreen = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-green").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetCyan = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-cyan").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetPurple = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-purple").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetMagenta = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-magenta").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetOrange = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-orange").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetGray = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-gray").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetLightGray = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-silver").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetBlack = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-black").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetLime = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-lime").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetLightBlue = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-light_blue").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetBrown = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-brown").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		WallCarpetPink = new BlockWallCarpet(Material.cloth).setBlockName("WallCarpet-pink").setHardness(dirt).setCreativeTab(TabMain).setLightOpacity(0);
		AncientHalfSlab = new BlockAncientSlab(false, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-ancient");
		AncientDoubleSlab = new BlockAncientSlab(true, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-ancient_double");
		ObsidianHalfSlab = new BlockObsidianSlab(false, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-obsidian");
		ObsidianDoubleSlab = new BlockObsidianSlab(true, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-obsidian_double");
		JadeHalfSlab = new BlockJadeSlab(false, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-jade");
		JadeDoubleSlab = new BlockJadeSlab(true, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-jade_double");
		QuartzHalfSlab = new BlockQuartzSlab(false, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-quartz");
		QuartzDoubleSlab = new BlockQuartzSlab(true, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-quartz_double");
		LapisHalfSlab = new BlockLapisSlab(false, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-lapis");
		LapisDoubleSlab = new BlockLapisSlab(true, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-lapis_double");
		DirtHalfSlab = new BlockDirtSlab(false, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-dirt");
		DirtDoubleSlab = new BlockDirtSlab(true, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-dirt_double");
		SnowHalfSlab = new BlockSnowSlab(false, Material.craftedSnow).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-snow");
		SnowDoubleSlab = new BlockSnowSlab(true, Material.craftedSnow).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-snow_double");
		EnderHalfSlab = new BlockEnderSlab(false, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-ender");
		EnderDoubleSlab = new BlockEnderSlab(true, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-ender_double");
		SandstoneHalfSlab = new BlockSandstoneSlab(false, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-sandstone");
		SandstoneDoubleSlab = new BlockSandstoneSlab(true, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-sandstone_double");
		ZigguratHalfSlab = new BlockZigguratSlab(false, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-ziggurat");
		ZigguratDoubleSlab = new BlockZigguratSlab(true, Material.rock).setHardness(stone).setCreativeTab(TabMain).setBlockName("AoCSlabs-ziggurat_double");
		SandstonePillar = new BlockAoCPillars(Material.rock, new String[] {"sandstone"}).setCreativeTab(TabMain).setHardness(stone).setBlockName("AoBPillars.sandstone");
		ChiseledSnowBricks = new BlockAoCChiseled(Material.craftedSnow).setBlockName("AoCChiseled-snow").setHardness(snow).setCreativeTab(TabMain);
		ChiseledSandstoneBricks = new BlockAoCChiseled(Material.rock).setBlockName("AoCChiseled-sandstone").setHardness(stone).setCreativeTab(TabMain);
		ChiseledAncientBricks= new BlockAoCChiseled(Material.rock).setBlockName("AoCChiseled-ancient").setHardness(stone).setCreativeTab(TabMain);
		ChiseledDirtBricks= new BlockAoCChiseled(Material.rock).setBlockName("AoCChiseled-dirt").setHardness(stone).setCreativeTab(TabMain);
		ChiseledQuartzBricks= new BlockAoCChiseled(Material.rock).setBlockName("AoCChiseled-quartz").setHardness(stone).setCreativeTab(TabMain);
		ChiseledLapisBricks= new BlockAoCChiseled(Material.rock).setBlockName("AoCChiseled-lapis").setHardness(stone).setCreativeTab(TabMain);
		ChiseledJadeBricks= new BlockAoCChiseled(Material.rock).setBlockName("AoCChiseled-jade").setHardness(stone).setCreativeTab(TabMain);
		ChiseledObsidianBricks= new BlockAoCChiseled(Material.rock).setBlockName("AoCChiseled-obsidian").setHardness(stone).setCreativeTab(TabMain);
		ChiseledEnderBricks= new BlockAoCChiseled(Material.rock).setBlockName("AoCChiseled-ender").setHardness(stone).setCreativeTab(TabMain);
		ChiseledZigguratBricks= new BlockAoCChiseled(Material.rock).setBlockName("AoCChiseled-ziggurat").setHardness(stone).setCreativeTab(TabMain);
		PineHalfSlab = new BlockPineSlab(false, Material.wood).setHardness(wood).setCreativeTab(TabMain).setBlockName("AoCSlabs-pine");
		PineDoubleSlab = new BlockPineSlab(true, Material.wood).setHardness(wood).setCreativeTab(TabMain).setBlockName("AoCSlabs-pine_double");
		PineWoodFence = new BlockAoCFence(AoCPlanks, Material.wood).setHardness(wood).setCreativeTab(TabMain).setBlockName("AoCFences-pine");
		RedTiles = new BlockAoCTiles(Material.rock).setBlockName("AoCTiles-red").setCreativeTab(TabMain).setHardness(stone);
		WhiteTiles = new BlockAoCTiles(Material.rock).setBlockName("AoCTiles-white").setCreativeTab(TabMain).setHardness(stone);
		BlueTiles = new BlockAoCTiles(Material.rock).setBlockName("AoCTiles-blue").setCreativeTab(TabMain).setHardness(stone);
		RedTileStairs = new BlockAoCStairs(Material.rock, RedTiles, 0).setCreativeTab(TabMain).setHardness(stone).setBlockName("StairTiles-red");
		WhiteTileStairs = new BlockAoCStairs(Material.rock, WhiteTiles, 0).setCreativeTab(TabMain).setHardness(stone).setBlockName("StairTiles-white");
		BlueTileStairs = new BlockAoCStairs(Material.rock, BlueTiles, 0).setCreativeTab(TabMain).setHardness(stone).setBlockName("StairTiles-blue");
		CyanTiles= new BlockAoCTiles(Material.rock).setBlockName("AoCTiles-cyan").setCreativeTab(TabMain).setHardness(stone);
		CyanTileStairs = new BlockAoCStairs(Material.rock, CyanTiles, 0).setCreativeTab(TabMain).setBlockName("StairTiles-cyan").setHardness(stone);
		Designer = new BlockDesigner(Material.rock, false).setCreativeTab(TabMain).setBlockName("Designer").setHardness(stone);
		WorkingDesigner = new BlockDesigner(Material.rock, true).setBlockName("WorkingDesigner").setHardness(stone);
		Ballista = new BlockBallista(Material.wood).setBlockName("Ballista").setHardness((wood / 6) * 5).setCreativeTab(TabMain);
		OliveLeaves = new BlockOliveLeaves(Material.leaves).setBlockName("AoBLeaves-olive").setHardness(dirt / 5 * 4).setCreativeTab(TabMain);
		/*ALWAYS ADD INITIALIZATIONS IN THE END*/	
	}
	
	
	public static void register(){
		registerBlock(LapisBricks);
		registerBlock(SmoothstoneBricks);
		registerBlock(AncientBricks);
		registerBlock(ObsidianBricks);
		registerBlock(QuartzBricks);
		registerBlock(JadeBricks);
		registerBlock(ZigguratBricks);
		registerBlock(SnowBricks);
		registerBlock(DirtBricks);
		registerBlock(SandstoneBricks);
		registerBlock(EnderBricks);
		registerBlock(BoneBlock);
		registerBlock(GobletBlock);
		registerBlock(PineLeaves);
		registerBlock(ConePineLeaves);
		registerBlock(ChainBlock);
		registerBlock(BronzeBlock);
		registerBlock(SteelBlock);
		registerBlock(RedSteelBlock);
		registerBlock(AlloyingTable);
		registerBlock(GrapeCrop);
		registerBlock(AsianDoor);
		registerBlock(Bindweed);
		registerBlock(JadePillar);
		registerBlock(StonebrickPillar);
		registerBlock(OldStonePillar);
		registerBlock(SmoothstonePillar);
		registerBlock(LapisPillar);
		registerBlock(ObsidianPillar);
		registerBlock(DirtPillar);
		registerBlock(EnderPillar);
		registerBlock(ZigguratPillar);
		registerBlock(SnowPillar);
		registerBlock(SandstoneBrickStairs);
		registerBlock(ZigguratBrickStairs);
		registerBlock(SmoothstoneStairs);
		registerBlock(EnderBrickStairs);
		registerBlock(AncientBrickStairs);
		registerBlock(LapisBrickStairs);
		registerBlock(QuartzBrickStairs);
		registerBlock(DirtBrickStairs);
		registerBlock(ObsidianBrickStairs);
		registerBlock(JadeBrickStairs);
		registerBlock(ObsidianBrickWall);
		registerBlock(SandstoneBrickWall);
		registerBlock(EnderBrickWall);
		registerBlock(SnowBrickWall);
		registerBlock(DirtBrickWall);
		registerBlock(QuartzBrickWall);
		registerBlock(StoneBrickWall);
		registerBlock(SmoothstoneBrickWall);
		registerBlock(JadeBrickWall);
		registerBlock(AncientBrickWall);
		registerBlock(ZigguratBrickWall);
		registerBlock(AoCLog, ItemAoBLogs.class);
		registerBlock(AoBSaplings, ItemAoBSaplings.class);
		registerBlock(AoCPlanks, ItemAoBPlanks.class);
		registerBlock(Altar);
		registerBlock(CopperOre);
		registerBlock(TinOre);
		registerBlock(WineGobletBlock);
		registerBlock(PineWoodStairs);
		registerBlock(WallCarpetWhite);
		registerBlock(WallCarpetRed);
		registerBlock(WallCarpetBlue);
		registerBlock(WallCarpetYellow);
		registerBlock(WallCarpetCyan);
		registerBlock(WallCarpetPurple);
		registerBlock(WallCarpetMagenta);
		registerBlock(WallCarpetOrange);
		registerBlock(WallCarpetGray);
		registerBlock(WallCarpetLightGray);
		registerBlock(WallCarpetBlack);
		registerBlock(WallCarpetLime);
		registerBlock(WallCarpetLightBlue);
		registerBlock(WallCarpetBrown);
		registerBlock(WallCarpetPink);
		registerBlock(WallCarpetGreen);
		registerBlock(AncientHalfSlab, ItemAncientSlab.class);
		registerBlock(AncientDoubleSlab, ItemAncientSlab.class);
		registerBlock(SandstoneHalfSlab, ItemSandstoneSlab.class);
		registerBlock(SandstoneDoubleSlab, ItemSandstoneSlab.class);
		registerBlock(JadeHalfSlab, ItemJadeSlab.class);
		registerBlock(JadeDoubleSlab, ItemJadeSlab.class);
		registerBlock(QuartzHalfSlab, ItemQuartzSlab.class);
		registerBlock(QuartzDoubleSlab, ItemQuartzSlab.class);
		registerBlock(ObsidianHalfSlab, ItemObsidianSlab.class);
		registerBlock(ObsidianDoubleSlab, ItemObsidianSlab.class);
		registerBlock(DirtHalfSlab, ItemDirtSlab.class);
		registerBlock(DirtDoubleSlab, ItemDirtSlab.class);
		registerBlock(SnowHalfSlab, ItemSnowSlab.class);
		registerBlock(SnowDoubleSlab, ItemSnowSlab.class);
		registerBlock(ZigguratHalfSlab, ItemZigguratSlab.class);
		registerBlock(ZigguratDoubleSlab, ItemZigguratSlab.class);
		registerBlock(SnowBrickStairs);
		registerBlock(LapisHalfSlab, ItemLapisSlab.class);
		registerBlock(LapisDoubleSlab, ItemLapisSlab.class);
		registerBlock(EnderHalfSlab, ItemEnderSlab.class);
		registerBlock(EnderDoubleSlab, ItemEnderSlab.class);
		registerBlock(SandstonePillar);
		registerBlock(ChiseledSandstoneBricks);
		registerBlock(ChiseledSnowBricks);
		registerBlock(ChiseledDirtBricks);
		registerBlock(ChiseledObsidianBricks);
		registerBlock(ChiseledZigguratBricks);
		registerBlock(ChiseledJadeBricks);
		registerBlock(ChiseledQuartzBricks);
		registerBlock(ChiseledAncientBricks);
		registerBlock(ChiseledEnderBricks);
		registerBlock(ChiseledLapisBricks);
		registerBlock(LapisBrickWall);
		registerBlock(PineHalfSlab, ItemPineSlab.class);
		registerBlock(PineDoubleSlab, ItemPineSlab.class);
		registerBlock(PineWoodFence);
		registerBlock(RedTiles);
		registerBlock(WhiteTiles);
		registerBlock(BlueTiles);
		registerBlock(RedTileStairs);
		registerBlock(BlueTileStairs);
		registerBlock(WhiteTileStairs);
		registerBlock(CyanTiles);
		registerBlock(CyanTileStairs);
		registerBlock(Designer);
		registerBlock(WorkingDesigner);
		registerBlock(Ballista);
		registerBlock(OliveLeaves);

	}
	
	private static void registerBlock(Block block, Class<? extends ItemBlock> itemclass) {
		GameRegistry.registerBlock(block, itemclass, block.getUnlocalizedName().substring(5));
	}
	
    private static void registerBlock(Block block){
		GameRegistry.registerBlock(block, block.getUnlocalizedName());
	}
    
}
